version: '3'

services:
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS
      - GF_AUTH_ANONYMOUS_ORG_NAME
      - GF_USERS_DEFAULT_THEME