[[servers]]
host = "{LDAP SERVER HOST NAME}"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "XUHL-TR\\%s"

search_filter = "(sAMAccountName=%s)"

search_base_dns = ["dc=xuhl-tr,dc=nhs,dc=uk"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"
